baseURL = 'https://echauvea.github.io'
languageCode = 'en'
title = 'Estelle Chauveau'

# [taxonomies]
# tag = "tags|"

theme = "hugo-ttl"
canonifyURLs = true
disqusShortname = 'echauvea'

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
