baseURL = 'https://echauve.github.io'
languageCode = 'fr'
title = 'Estelle Chauveau Homepage'

# [taxonomies]
# tag = "tags|"

theme = "hugo-ttl"
canonifyURLs = true
disqusShortname = 'echauvea'

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
